version: '3.8'

services:
  # Worker Manager - Coordena os workers
  worker-manager:
    build: .
    image: ai-trading:latest
    container_name: ai-worker-manager
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - WORKER_MODE=manager
      - TOTAL_WORKERS=4
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    command: ["python", "worker_manager.py"]
    restart: unless-stopped

  # Workers para treinamento paralelo
  worker-1:
    build: .
    image: ai-trading:latest
    container_name: ai-worker-1
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - WORKER_ID=1
      - TOTAL_WORKERS=4
      - WORKER_MODE=training
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    command: ["python", "worker_training.py"]
    restart: unless-stopped
    depends_on:
      - worker-manager

  worker-2:
    build: .
    image: ai-trading:latest
    container_name: ai-worker-2
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - WORKER_ID=2
      - TOTAL_WORKERS=4
      - WORKER_MODE=training
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    command: ["python", "worker_training.py"]
    restart: unless-stopped
    depends_on:
      - worker-manager

  worker-3:
    build: .
    image: ai-trading:latest
    container_name: ai-worker-3
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - WORKER_ID=3
      - TOTAL_WORKERS=4
      - WORKER_MODE=training
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    command: ["python", "worker_training.py"]
    restart: unless-stopped
    depends_on:
      - worker-manager

  worker-4:
    build: .
    image: ai-trading:latest
    container_name: ai-worker-4
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - WORKER_ID=4
      - TOTAL_WORKERS=4
      - WORKER_MODE=training
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    command: ["python", "worker_training.py"]
    restart: unless-stopped
    depends_on:
      - worker-manager

  # Dashboard para monitorar treinamento
  training-dashboard:
    build: .
    image: ai-trading:latest
    container_name: ai-training-dashboard
    ports:
      - "8502:8501"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - DASHBOARD_MODE=training
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    command: ["streamlit", "run", "training_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
    restart: unless-stopped
